### ISSUE TITLE
[FEAT] 어플리케이션 공통 예외/에러 클래스 개발

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere#54]
## 📝 Description
어플리케이션 예외/에러 공통 로직 개발

## 📍 Todo
- [ ] 공통 Exception 개발
- [ ] 공통 Error 응답 개발
- [ ] 전역 Exception Handler 개발

## 📢 To Reviewers
에러 응답은 ErrorResponse를 ResponseEntity 바디로

서비스 구현시 발생하는데 에러는 모두 공통 Exception을 상속
