### ISSUE TITLE
[FEAT] 재고 목록 조회 및 수정/삭제/검색 기능 개발

### ISSUE THREAD

**Issue by jang643** [8-palbochae/seahere#65]
## 📝 Description
재고 목록 조회 및 수정/삭제/검색 기능 컴포넌트 구현 및 백엔드 연결

## 📍 Todo
- [x] 재고 목록 조회 기능 개발
- [ ] 재고 목록 검색 기능 개발
- [ ] 재고 목록 삭제 기능 개발
- [ ] 재고 목록 수정 기능 개발
